### ISSUE TITLE
STTM Incorporated LFTM and jLDADMM packages without any acknowledgement

### ISSUE THREAD

**Issue by datquocnguyen** [qiang2100/STTM#1]
Hi,
I just find out that the STTM package incorporated my [LFTM](https://github.com/datquocnguyen/LFTM) and [jLDADMM](https://github.com/datquocnguyen/jLDADMM) packages without any acknowledgement. 

In particular, STMM used my implementations for LDA, DMM, LF-LDA and LF-DMM, including 8 Java files: LDA.java, DMM.java, LFLDA.java, LFDMM.java, LDA_Inf.java, DMM_Inf.java, LFLDA_Inf.java and LFDMM_Inf.java. 

I hope you can mention this fact by referring to my packages in your `Readme` file in the Citation section: 

"The implementations for LF-LDA and LF-DMM and for LDA and DMM are incorporated from the [LFTM](https://github.com/datquocnguyen/LFTM) and [jLDADMM](https://github.com/datquocnguyen/jLDADMM) packages, respectively. See these two packages for more details."

Thank you.
Best,
Dat.

**Comment by qiang2100** [comment]
Thanks for your reminder. Now, I add your package LFTM and jLDADMM in the "Readme" file.
