### ISSUE TITLE
Error: the number of documents is different to the number of labels!

### ISSUE THREAD

**Issue by clairett** [qiang2100/STTM#5]
I came across this error while using GoogleNews data for classification eval. I found the input text and label data contain 11109 documents, while the theta file has 11108 documents. Could you please help me to check what goes wrong? I really appreciate your help.

**Comment by qiang2100** [comment]
Thanks for you comment. Because  one line is null in the datafile. Now I delete this line, revised the file "GoogleNews.txt" and "GoogleNew_Label.txt". You can re-download these files.

**Comment by clairett** [comment]
Thank you so much, it works like a magic
