### ISSUE TITLE
Question about LDA and WNTM alpha parameters

### ISSUE THREAD

**Issue by jrmazarura** [qiang2100/STTM#8]
Dear Jipeng 

First of all I would like to thank you for creating STTM. It is really amazing. 

I have a question about the LDA and WNTM models. The default alpha for these models is 50/ntopics and not 0.1. I would like to use apha=0.1 but the codes are refusing to change the value of alpha from the default. When I run the following code, alpha is set to 5 (=50/ntopics) and not 0.1 as desired:

java -jar jar/STTM.jar -model LDA -corpus dataset/SearchSnippets.txt -ntopics 10 -niters 10 -alpha 0.1 -name SearchSnippetsTest

How do I change the alpha value?

**Comment by qiang2100** [comment]
Thanks for your question. If you run the source code, I modified the file "STTM.java".  The details is:
"in STTM.java, the input "alpha" of LDA is set as 50/ntopics"

**Comment by jrmazarura** [comment]
Hi. I still can't change the alpha to 0.1. It is still using 50/ntopics even when I include -alpha 0.1.

**Comment by qiang2100** [comment]
If you run "STTM.jar", please re-download "STTM.jar" from "jar" file. If you run the source code, please re-download "STTM.java" from "src" file.

**Comment by jrmazarura** [comment]
Thank you so much. It works now.
