### ISSUE TITLE
GPUDMM works only as DMM

### ISSUE THREAD

**Issue by Thomas1808** [qiang2100/STTM#9]
Hi Jipeng,

first of all I would like to thank you. Your STTM package is great.

I was trying to train a GPUDMM model in an own Java application. To create an object from the class GPUDMM I had to specify the parameters "threshold", "weight" and "filterSize".  Unfortunately, these parameters are not passed from the GPUDMM constructor to the corresponding variable of the object.
By carefully examine the code I found, that for the "threshold" this does not matter since only the method "computeSchema" uses the value and this method is called in the constructer and receives the threshold value. 
However, for the "filterSize" and "weight" this is different. By not passing the "filterSize" to the Object the condition "(tmpMap.size() > filterSize)" in line 303 is always true which leads to an empty schemaMap. Furthermore not passing "weight" makes the GPUDMM to a normal DMM as mentioned by the Authors of the GPUDMM article "Note that, when µ = 0, GPU-DMM is equivalent to the DMM model.". See page 9 left column.

Unfortunately, simply add the following lines of code in the constructor leads to an error during inference of the GPUDMM. The reason is an ArrayIndexOutOfBounce Exception, which is connected to the "weight" attribute.
this.weight = weight;
this.filterSize= filterSize;

Are my thoughts correct or do I miss something?
Thank you in advance for any help.

Regards
Thomas

**Comment by qiang2100** [comment]
Thanks for your suggestions. I revised the code of GPUDMM.
